# Generated by Django 5.2.11 on 2026-02-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list[str] = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "company_name",
                    models.CharField(default="codex_dlc_company", max_length=255, verbose_name="Company Name"),
                ),
                (
                    "company_name_en",
                    models.CharField(
                        default="codex_dlc_company", max_length=255, null=True, verbose_name="Company Name"
                    ),
                ),
                (
                    "company_name_de",
                    models.CharField(
                        default="codex_dlc_company", max_length=255, null=True, verbose_name="Company Name"
                    ),
                ),
                (
                    "company_name_ru",
                    models.CharField(
                        default="codex_dlc_company", max_length=255, null=True, verbose_name="Company Name"
                    ),
                ),
                (
                    "site_base_url",
                    models.URLField(
                        blank=True,
                        help_text="If empty, uses value from .env (SITE_BASE_URL)",
                        verbose_name="Site Base URL",
                    ),
                ),
                (
                    "logo_url",
                    models.CharField(
                        blank=True, default="/static/img/logo.webp", max_length=500, verbose_name="Logo URL"
                    ),
                ),
                ("phone", models.CharField(default="+1 234 567 890", max_length=50, verbose_name="Phone")),
                (
                    "email",
                    models.EmailField(default="info@codex_dlc_company.com", max_length=254, verbose_name="Email"),
                ),
                ("address", models.CharField(blank=True, max_length=255, verbose_name="Address")),
                ("address_en", models.CharField(blank=True, max_length=255, null=True, verbose_name="Address")),
                ("address_de", models.CharField(blank=True, max_length=255, null=True, verbose_name="Address")),
                ("address_ru", models.CharField(blank=True, max_length=255, null=True, verbose_name="Address")),
                (
                    "working_hours",
                    models.CharField(default="Mo-Fr: 09:00 - 18:00", max_length=100, verbose_name="Working Hours"),
                ),
                (
                    "working_hours_en",
                    models.CharField(
                        default="Mo-Fr: 09:00 - 18:00", max_length=100, null=True, verbose_name="Working Hours"
                    ),
                ),
                (
                    "working_hours_de",
                    models.CharField(
                        default="Mo-Fr: 09:00 - 18:00", max_length=100, null=True, verbose_name="Working Hours"
                    ),
                ),
                (
                    "working_hours_ru",
                    models.CharField(
                        default="Mo-Fr: 09:00 - 18:00", max_length=100, null=True, verbose_name="Working Hours"
                    ),
                ),
                ("instagram_url", models.URLField(blank=True, verbose_name="Instagram URL")),
                ("facebook_url", models.URLField(blank=True, verbose_name="Facebook URL")),
                ("telegram_channel_url", models.URLField(blank=True, verbose_name="Telegram Channel URL")),
                (
                    "telegram_client_bot_url",
                    models.URLField(blank=True, verbose_name="Telegram Client Bot/Support URL"),
                ),
                ("whatsapp_url", models.URLField(blank=True, verbose_name="WhatsApp URL")),
                (
                    "meta_title",
                    models.CharField(default="codex_dlc_company", max_length=255, verbose_name="Default Meta Title"),
                ),
                (
                    "meta_title_en",
                    models.CharField(
                        default="codex_dlc_company", max_length=255, null=True, verbose_name="Default Meta Title"
                    ),
                ),
                (
                    "meta_title_de",
                    models.CharField(
                        default="codex_dlc_company", max_length=255, null=True, verbose_name="Default Meta Title"
                    ),
                ),
                (
                    "meta_title_ru",
                    models.CharField(
                        default="codex_dlc_company", max_length=255, null=True, verbose_name="Default Meta Title"
                    ),
                ),
                ("meta_description", models.TextField(blank=True, verbose_name="Default Meta Description")),
                (
                    "meta_description_en",
                    models.TextField(blank=True, null=True, verbose_name="Default Meta Description"),
                ),
                (
                    "meta_description_de",
                    models.TextField(blank=True, null=True, verbose_name="Default Meta Description"),
                ),
                (
                    "meta_description_ru",
                    models.TextField(blank=True, null=True, verbose_name="Default Meta Description"),
                ),
                (
                    "favicon_url",
                    models.CharField(default="/static/img/favicon.ico", max_length=500, verbose_name="Favicon URL"),
                ),
                (
                    "og_image_url",
                    models.URLField(
                        blank=True,
                        help_text="Open Graph share image (1200x630px recommended)",
                        verbose_name="OG Image URL",
                    ),
                ),
                (
                    "canonical_domain",
                    models.URLField(
                        blank=True,
                        help_text="Primary domain for canonical/hreflang tags (e.g. https://codexdlc.com). Falls back to CANONICAL_DOMAIN from .env",
                        verbose_name="Canonical Domain",
                    ),
                ),
                (
                    "ga4_measurement_id",
                    models.CharField(
                        blank=True, help_text="e.g. G-XXXXXXXXXX", max_length=50, verbose_name="GA4 Measurement ID"
                    ),
                ),
                (
                    "gtm_container_id",
                    models.CharField(
                        blank=True, help_text="e.g. GTM-XXXXXXX", max_length=50, verbose_name="GTM Container ID"
                    ),
                ),
                (
                    "geo_lat",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True, verbose_name="Latitude"
                    ),
                ),
                (
                    "geo_lng",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True, verbose_name="Longitude"
                    ),
                ),
                (
                    "telegram_admin_channel_id",
                    models.CharField(
                        blank=True,
                        help_text="Telegram ID for internal notifications (e.g. -100...)",
                        max_length=100,
                        verbose_name="Admin Channel ID (Internal)",
                    ),
                ),
                (
                    "telegram_technical_bot_username",
                    models.CharField(
                        blank=True,
                        help_text="The bot that sends admin alerts",
                        max_length=100,
                        verbose_name="Technical Bot Username",
                    ),
                ),
                (
                    "telegram_notification_topic_id",
                    models.IntegerField(
                        blank=True,
                        help_text="The topic ID in the admin channel for general notifications",
                        null=True,
                        verbose_name="Notification Topic ID",
                    ),
                ),
                (
                    "telegram_topics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Mapping of services to Telegram Topic IDs (e.g. {'hair': 2, 'nails': 4})",
                        verbose_name="Telegram Topics Map",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="StaticTranslation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "key",
                    models.CharField(
                        help_text="Unique identifier used in templates (e.g., 'home_hero_title')",
                        max_length=100,
                        unique=True,
                        verbose_name="Key",
                    ),
                ),
                ("text", models.TextField(verbose_name="Text Content")),
                ("text_en", models.TextField(null=True, verbose_name="Text Content")),
                ("text_de", models.TextField(null=True, verbose_name="Text Content")),
                ("text_ru", models.TextField(null=True, verbose_name="Text Content")),
                ("description", models.CharField(blank=True, max_length=255, verbose_name="Description")),
            ],
            options={
                "verbose_name": "Static Translation",
                "verbose_name_plural": "Static Translations",
                "ordering": ["key"],
            },
        ),
    ]
