# Generated by Django 5.2.11 on 2026-02-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0001_add_seo_analytics_geo_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="site_mode",
            field=models.CharField(
                choices=[("research", "Research"), ("sales", "Sales")],
                default="research",
                help_text="'research' = email/survey CTAs, 'sales' = pricing/consultation CTAs",
                max_length=20,
                verbose_name="Site Mode",
            ),
        ),
    ]
