# Generated by Django 5.2.11 on 2026-02-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PricingPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked, this item will be completely hidden from the site.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked, shows 'Temporarily Unavailable' (e.g. no masters).",
                        verbose_name="Available for Booking",
                    ),
                ),
                (
                    "is_planned",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, shows 'Coming Soon' badge.",
                        verbose_name="Planned / Coming Soon",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[("waas", "Website as a Service"), ("automation", "Automation")],
                        max_length=20,
                        verbose_name="Service",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Plan Name")),
                ("name_en", models.CharField(max_length=100, null=True, verbose_name="Plan Name")),
                ("name_de", models.CharField(max_length=100, null=True, verbose_name="Plan Name")),
                ("name_ru", models.CharField(max_length=100, null=True, verbose_name="Plan Name")),
                (
                    "price_label",
                    models.CharField(
                        help_text="Display price string, e.g. 'от €59 / мес'", max_length=100, verbose_name="Price"
                    ),
                ),
                (
                    "price_label_en",
                    models.CharField(
                        help_text="Display price string, e.g. 'от €59 / мес'",
                        max_length=100,
                        null=True,
                        verbose_name="Price",
                    ),
                ),
                (
                    "price_label_de",
                    models.CharField(
                        help_text="Display price string, e.g. 'от €59 / мес'",
                        max_length=100,
                        null=True,
                        verbose_name="Price",
                    ),
                ),
                (
                    "price_label_ru",
                    models.CharField(
                        help_text="Display price string, e.g. 'от €59 / мес'",
                        max_length=100,
                        null=True,
                        verbose_name="Price",
                    ),
                ),
                ("feat_1", models.CharField(blank=True, max_length=255, verbose_name="Feature 1")),
                ("feat_1_en", models.CharField(blank=True, max_length=255, null=True, verbose_name="Feature 1")),
                ("feat_1_de", models.CharField(blank=True, max_length=255, null=True, verbose_name="Feature 1")),
                ("feat_1_ru", models.CharField(blank=True, max_length=255, null=True, verbose_name="Feature 1")),
                ("feat_2", models.CharField(blank=True, max_length=255, verbose_name="Feature 2")),
                ("feat_2_en", models.CharField(blank=True, max_length=255, null=True, verbose_name="Feature 2")),
                ("feat_2_de", models.CharField(blank=True, max_length=255, null=True, verbose_name="Feature 2")),
                ("feat_2_ru", models.CharField(blank=True, max_length=255, null=True, verbose_name="Feature 2")),
                ("feat_3", models.CharField(blank=True, max_length=255, verbose_name="Feature 3")),
                ("feat_3_en", models.CharField(blank=True, max_length=255, null=True, verbose_name="Feature 3")),
                ("feat_3_de", models.CharField(blank=True, max_length=255, null=True, verbose_name="Feature 3")),
                ("feat_3_ru", models.CharField(blank=True, max_length=255, null=True, verbose_name="Feature 3")),
                ("cta_label", models.CharField(default="Choose", max_length=100, verbose_name="CTA Label")),
                (
                    "cta_label_en",
                    models.CharField(default="Choose", max_length=100, null=True, verbose_name="CTA Label"),
                ),
                (
                    "cta_label_de",
                    models.CharField(default="Choose", max_length=100, null=True, verbose_name="CTA Label"),
                ),
                (
                    "cta_label_ru",
                    models.CharField(default="Choose", max_length=100, null=True, verbose_name="CTA Label"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Highlighted plan (e.g. most popular)", verbose_name="Featured"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Pricing Plan",
                "verbose_name_plural": "Pricing Plans",
                "ordering": ["service", "order"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked, this item will be completely hidden from the site.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked, shows 'Temporarily Unavailable' (e.g. no masters).",
                        verbose_name="Available for Booking",
                    ),
                ),
                (
                    "is_planned",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, shows 'Coming Soon' badge.",
                        verbose_name="Planned / Coming Soon",
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        help_text="Browser tab title. Defaults to object title if empty.",
                        max_length=255,
                        verbose_name="SEO Title",
                    ),
                ),
                (
                    "seo_description",
                    models.TextField(
                        blank=True, help_text="Meta description for search engines.", verbose_name="SEO Description"
                    ),
                ),
                (
                    "seo_image",
                    models.ImageField(
                        blank=True,
                        help_text="Image for social media sharing (1200x630px recommended).",
                        null=True,
                        upload_to="seo/",
                        verbose_name="OG Image",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("name_en", models.CharField(max_length=255, null=True, verbose_name="Name")),
                ("name_de", models.CharField(max_length=255, null=True, verbose_name="Name")),
                ("name_ru", models.CharField(max_length=255, null=True, verbose_name="Name")),
                ("niche", models.CharField(max_length=100, verbose_name="Niche")),
                ("niche_en", models.CharField(max_length=100, null=True, verbose_name="Niche")),
                ("niche_de", models.CharField(max_length=100, null=True, verbose_name="Niche")),
                ("niche_ru", models.CharField(max_length=100, null=True, verbose_name="Niche")),
                ("city", models.CharField(blank=True, max_length=100, verbose_name="City")),
                ("city_en", models.CharField(blank=True, max_length=100, null=True, verbose_name="City")),
                ("city_de", models.CharField(blank=True, max_length=100, null=True, verbose_name="City")),
                ("city_ru", models.CharField(blank=True, max_length=100, null=True, verbose_name="City")),
                (
                    "status",
                    models.CharField(
                        choices=[("live", "Live"), ("taken", "Taken"), ("free", "Free")],
                        default="free",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "preview_url",
                    models.URLField(
                        blank=True, help_text="Clickable prototype link (48h version)", verbose_name="Prototype URL"
                    ),
                ),
                (
                    "site_url",
                    models.URLField(
                        blank=True, help_text="Link to the live production site", verbose_name="Live Site URL"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Preview image for bento card",
                        null=True,
                        upload_to="projects/",
                        verbose_name="Thumbnail",
                    ),
                ),
                (
                    "has_automation",
                    models.BooleanField(
                        default=False,
                        help_text="If True, shown on /services/automation/ page",
                        verbose_name="Has Automation",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["order", "name"],
            },
        ),
    ]
